Models/FormInputs/Subject.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using System.Text.RegularExpressions;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace vote_standalone.Models.FormInputs.Subject
{
    public class Create
    {
        public const int TITLE_LENGTH_MIN = 1;
        public const int TITLE_LENGTH_MAX = 100;
        public const int ARTIST_LENGTH_MIN = 1;
        public const int ARTIST_LENGTH_MAX = 100;
        public const int URL_LENGTH_MIN = 1;
        public const int URL_LENGTH_MAX = 200;
        public const int COMMENT_LENGTH_MIN = 1;
        public const int COMMENT_LENGTH_MAX = 50;

        [Required] public string Title { get; set; }
        [Required] public string Artist { get; set; }
        [Required] public string Url { get; set; }
        public string Comment { get; set; }

        public void Validate()
        {
            if (Title == null || Title.Length < TITLE_LENGTH_MIN || TITLE_LENGTH_MAX < Title.Length)
            {
                throw new Exception();
            }
            if (Artist == null || Artist.Length < ARTIST_LENGTH_MIN || ARTIST_LENGTH_MAX < Artist.Length)
            {
                throw new Exception();
            }
            if (Url == null || Url.Length < URL_LENGTH_MIN || URL_LENGTH_MAX < Url.Length)
            {
                throw new Exception();
            }
            if (Comment != null && (Comment.Length < COMMENT_LENGTH_MIN || COMMENT_LENGTH_MAX < Comment.Length))
            {
                throw new Exception();
            }
        }
    }
    public class Vote
    {
        public const int POINT_LENGTH_MIN = 1;
        public const int POINT_LENGTH_MAX = 100;
        public const int COMMENT_LENGTH_MIN = 1;
        public const int COMMENT_LENGTH_MAX = 50;

        [Required] public string SubjectId { get; set; }
        [Required] public string Point { get; set; }
        public string Comment { get; set; }

        public void Validate()
        {
            if (SubjectId == null)
            {
                throw new Exception();
            }
            if (Point == null || Point.Length < POINT_LENGTH_MIN || POINT_LENGTH_MAX < Point.Length)
            {
                throw new Exception();
            }
            if (Comment != null && (Comment.Length < COMMENT_LENGTH_MIN || COMMENT_LENGTH_MAX < Comment.Length))
            {
                throw new Exception();
            }
        }
    }
}

Models/Sqlite3/Subjects.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace vote_standalone.Models.Sqlite
{
    public class Subjects
    {
        public static bool IsExist(string title, string artist)
        {
            return Convert.ToInt32(MySqlite.GetOne(
                "select count(1) from subjects " +
                "where title = ? and artist = ? ",
                new object[] { title, artist }
            )) >= 1;
        }
        public static List<Dictionary<string, object>> GetAll()
        {
            return MySqlite.GetAll(
                "select id, user_id, title, artist, url, comment, created_at from subjects " +
                "where is_disabled = 0 " +
                "order by id asc "
            );
        }
        public static List<Dictionary<string, object>> GetAllWithMyVote(int? userId)
        {
            return MySqlite.GetAll(
                "select subjects.id as subject_id, subjects.user_id as user_id, "+
                "title, artist, url, subjects.comment as subject_comment, "+
                "subject_votes.comment as vote_comment, point, subject_votes.id as vote_id " +
                "from subjects " +
                "left join subject_votes on "+
                "subject_votes.subject_id = subjects.id " +
                "where subject_votes.user_id = ? or subject_votes.user_id is null ",
                new object[] { userId }
            );
        }
        public static List<Dictionary<string, object>> GetMine(int? userId)
        {
            return MySqlite.GetAll(
                "select id, user_id, title, artist, url, comment, created_at from subjects " +
                "where user_id = ? and is_disabled = 0 " +
                "order by id asc ",
                new object[] { userId }
            );
        }
        public static bool Create(int? userId, string title, string artist, string url, string comment)
        {
            if (IsExist(title, artist)) return false;

            return MySqlite.Execute(
                "insert into subjects " +
                "(user_id, title, artist, url, comment, created_at) values " +
                "(?, ?, ?, ?, ?, ?) ",
                new object[] { userId, title, artist, url, comment, Utility.GetDatetime() }
            ) >= 1;
        }
    }
}

Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using vote_standalone.Models;
using vote_standalone.Models.Sqlite;
using vote_standalone.Models.FormInputs.Subject;


namespace vote_standalone.Controllers
{
    public class SubjectsController : Controller
    {
        [Route("subjects/input")]
        public IActionResult Input()
        {
            if (!MyUser.Login(Cookie.GetUuid()))
            {
                throw new Exception();
            }

            ViewData["MySubjects"] = Subjects.GetMine(MyUser.GetId());

            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 配信投票</title>
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://fonts.googleapis.com/css2?family=Mitr:wght@600&display=swap" rel="stylesheet">    
    <link rel="stylesheet" href="/css/site.css" />
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/js/coffeejs/utl.js"></script>
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Xsrf
@functions{
    public string GetAntiXsrfRequestToken()
    {
        return Xsrf.GetAndStoreTokens(Context).RequestToken;
    }
}

</head>
<body>
<input type="hidden" id="RequestVerificationToken" 
       name="RequestVerificationToken" value="@GetAntiXsrfRequestToken()">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">配信投票</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">トップ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subjects" asp-action="Input">項目登録</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Subject.cshtml
@{
    var SubjectId = ViewData["SubjectId"];
    var SongTitle = ViewData["SongTitle"];
    var Artist = ViewData["Artist"];
    var Url = ViewData["Url"];
    var SubjectComment = ViewData["SubjectComment"];
    var PointAverage = ViewData["PointAverage"];
    var VotePoint = ViewData["VotePoint"];
    var VoteComment = ViewData["VoteComment"];
}
    <div class="card border-dark subject">
        <table class="table table-bordered table-striped">
            <tr>
                <th>曲名</th>
                <td>@(SongTitle)</td>
            </tr>
            <tr>
                <th>アーティスト名</th>
                <td>@(Artist)</td>
            </tr>
            <tr>
                <th>URL</th>
                <td>@(Url)</td>
            </tr>
            <tr>
                <th>コメント</th>
                <td>@(SubjectComment)</td>
            </tr>
            <tr>
                <th>平均点</th>
                <td>@(PointAverage)</td>
            </tr>
        </table>

        <div class="center">
            <input type="text" subject_id="@(SubjectId)" class="point" value="@(VotePoint)" />
            <span class="point_text">pts.</span>
        </div>
        <div class="center">
            <input type="range" subject_id="@(SubjectId)" class="slider" value="@(VotePoint)" min="@(vote_standalone.Models.FormInputs.Subject.Vote.POINT_LENGTH_MIN)" max="@(vote_standalone.Models.FormInputs.Subject.Vote.POINT_LENGTH_MAX)" step="1" />
        </div>
        <div class="center">
            <input type="text" subject_id="@(SubjectId)" class="comment form-control" maxlength="50"  value="@(VoteComment)" placeholder="任意　コメント@(vote_standalone.Models.FormInputs.Subject.Vote.COMMENT_LENGTH_MAX)文字まで" />
        </div>
        <div class="center">
            <button class="btn btn-hg btn-primary vote" subject_id="@(SubjectId)">投票</button>
        </div>
    </div>